### ISSUE TITLE
comparison vs VimGym?

### ISSUE THREAD

**Issue by mmikeww** [dankilman/vim-kata#1]
reason to use yours instead of
https://github.com/dahu/VimGym
?

**Comment by dankilman** [comment]
I wasn't aware of its existence to be honest 😅.
If I were, I'd likely use it intead of rolling my own.

Considering I am past that, I'd say using vim-kata is perhaps more likely to be actively worked on, in the near futute at the very least. 

I see that it implements book keeping of times which is exactly what I wanted to add next 🙃.

Some of the exercises are actually identical in both projects! This is likely due to both being taken from VimGolf.

**Comment by mmikeww** [comment]
ahhh haha makes sense. GL with this, i'm on windows so probably stick with VimGym, i like that you've included much more exercises
